global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'algoo-api'
    static_configs:
      - targets: ['localhost:8888', 'localhost:9999']

  - job_name: 'postgres'
    static_configs:
      - targets: ['localhost:9187']  # PostgreSQL exporter address

  - job_name: 'redis'
    static_configs:
      - targets: ['localhost:9121']  # Redis exporter address

  - job_name: 'influxdb'
    static_configs:
      - targets: ['localhost:8086']  # Replace with actual InfluxDB metrics endpoint port if different
